services:
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messenger
    env_file: .env
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:

